import { buildHtml } from '../../../lib/template';
export function buildHtml(data: Record<string, any>) {
  const esc = (s: any) =>
    String(s ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

  const d: any = {};
  for (const [k, v] of Object.entries(data)) d[k] = typeof v === 'string' ? esc(v) : v;

  const fmt = (n: any) => esc(n);

  const earnRows = (d.earnings || [])
    .map((r: any) => `<tr><td>${esc(r.label)}</td><td class="rightText">₦ ${fmt(r.amount)}</td></tr>`)
    .join('');
  const dedRows = (d.deductions || [])
    .map((r: any) => `<tr><td>${esc(r.label)}</td><td class="rightText">₦ ${fmt(r.amount)}</td></tr>`)
    .join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Payslip - ${d.company_name} - ${d.payslip_month}</title>
<style>
  body { font-family: Arial, Helvetica, sans-serif; color:#222; margin:18px; }
  .header { display:flex; justify-content:space-between; align-items:center; margin-bottom:12px; }
  .brand { display:flex; align-items:center; gap:12px; }
  .logo { width:70px; height:auto; }
  .company { font-weight:700; }
  .small { font-size:12px; color:#666; }
  .meta { text-align:right; font-size:13px; }
  .box { border:1px solid #c9c9c9; padding:14px; border-radius:6px; margin-bottom:18px; }
  .row { display:flex; justify-content:space-between; }
  .left { width:64%; }
  .right { width:34%; text-align:right; }
  .summary { display:flex; gap:8px; margin-bottom:6px; align-items:center; }
  .summary label { width:160px; color:#444; }
  .employee-number { font-weight:700; padding:6px 10px; border:1px dashed #bbb; background:#fafafa; }
  .grid { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th, td { padding:8px 10px; border-bottom:1px dashed #e6e6e6; }
  .rightText { text-align:right; }
  .net { font-weight:700; font-size:20px; margin-top:10px; }
  footer { margin-top:18px; font-size:11px; color:#666; }
</style>
</head>
<body>
  <div class="header">
    <div class="brand">
      <img class="logo" src="/images/logo.png" alt="logo"/>
      <div>
        <div class="company">${d.company_name}</div>
        <div class="small">${d.company_address}</div>
      </div>
    </div>
    <div class="meta">Payslip for the month<br/><strong>${d.payslip_month}</strong></div>
  </div>

  <div class="box">
    <div class="row">
      <div class="left">
        <div class="summary"><label>Employee Name :</label><div>${d.employee_name}</div></div>
        <div class="summary"><label>Employee's Number :</label><div class="employee-number">${d.employee_number}</div></div>
        <div class="summary"><label>Pay Period :</label><div>${d.pay_period}</div></div>
        <div class="summary"><label>Loss of Pay Days :</label><div>${d.loss_of_pay_days}</div></div>
      </div>
      <div class="right">
        <div><strong>Paid Days :</strong> ${d.paid_days}</div>
        <div style="height:8px;"></div>
        <div><strong>Pay Date :</strong> ${d.pay_date}</div>
      </div>
    </div>
  </div>

  <div class="grid">
    <div>
      <table>
        <tr><th style="text-align:left">Earnings</th><th class="rightText">Amount</th></tr>
        ${earnRows}
        <tr><td><strong>Gross Earnings</strong></td><td class="rightText"><strong>₦ ${d.gross_earnings}</strong></td></tr>
      </table>
    </div>
    <div>
      <table>
        <tr><th style="text-align:left">Deductions</th><th class="rightText">Amount</th></tr>
        ${dedRows}
        <tr><td><strong>Total Deductions</strong></td><td class="rightText"><strong>₦ ${d.total_deductions}</strong></td></tr>
      </table>
    </div>
  </div>

  <div class="net">Net Payable : ₦ ${d.net_payable}</div>
  <div class="small">Amount in words : ${d.amount_in_words}</div>
  <div style="margin-top:8px;"><strong>Notes :</strong><br/>${d.notes}</div>

  <footer>Generated by Bridgeocean Payslip Generator</footer>
</body>
</html>`;
}
